# example pod that will crashloop for integration test of CrashLoopBackOffRescheduler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      busybox: "true"
  template:
    metadata:
      labels:
        busybox: "true"
      annotations:
        kube-remediator/CrashLoopBackOffRemediator: "true"
    spec:
      containers:
        - image: busybox
          name: busybox
          command: ["this-is-bad"]
